<?php

print_r($_FILES);



	if(isset($_POST['ABSPATH'])){

	if ( ! function_exists( 'wp_handle_upload' ) ) {
    	require_once( $_POST['ABSPATH'] . 'wp-admin/includes/file.php' );
	}

	 $uploadedfile = $_FILES['image'];

	$file_name = $_FILES['image']['name'];
	$upload_overrides = array( 'test_form' => false );

	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

	if ( $movefile && ! isset( $movefile['error'] ) ) {
	    echo "<script>alert('File is valid, and was successfully uploaded')</script>";	   
	} else {
	    /**
	     * Error generated by _wp_handle_upload()
	     * @see _wp_handle_upload() in wp-admin/includes/file.php
	     */
	     echo "<script>alert('".$movefile['error']."')</script>";	    
	}	 
}
		exit;
			// populating database
			$title=$file_name;
			$category=$_POST['category'];
			$teacher_id = $_SESSION['teacher'] = "12";
			$wpdb->insert( 
					'wp_download_area', 
					array( 
						'title' => $title,
						'date' => date('y-m-d H:i:s'), 
						'file' => $movefile['url'],
						'category' => $category,					
						'status' =>  '1',
						'teacher_id' => $teacher_id,		
					)
				);
	

 ?>